### ISSUE TITLE
ImportError: cannot import name 'commands' from partially initialized module 'tsbot' (most likely due to a circular import) (C:\Users\admin\PycharmProjects\TS3Bot\.venv\lib\site-packages\tsbot\__init__.py)

### ISSUE THREAD

**Issue by Makzlol** [jykob/TSBot#43]
Every time you run any sample code of this library, this error occurs

**Comment by jykob** [comment]
This was caused by improper packaging.
Pushed new patch version `1.2.1` and yanked affected version (`1.2.0`).

Fix commit: 1866c79
